/**
 * Dagupan City Barangays
 * List of all barangays in Dagupan, Pangasinan
 */

export const DAGUPAN_BARANGAYS = [
  'Acubans',
  'Andaya',
  'Bacayao',
  'Bonuan',
  'Bonuan-Binacayan',
  'Bolosan',
  'Burgos',
  'Calasibacan',
  'Camuning',
  'Central',
  'Chumabol',
  'Coloma',
  'Cruces',
  'Culat',
  'Dewey',
  'Dinalaahan',
  'Dorongan',
  'El Nido',
  'Espino',
  'Farm-A',
  'Famy',
  'Favorata',
  'Florida',
  'Fontan',
  'Gat-Agao',
  'Gila',
  'Gorosariung',
  'Guevet',
  'Guinobatan',
  'Herrera',
  'Horadada-Palaris',
  'Hossagan',
  'Javellana',
  'La Paz',
  'Langyahan',
  'Lasip',
  'Likabtan',
  'Linging',
  'Loboo',
  'Lolomboy',
  'Lucao',
  'Lugui',
  'Lunghi',
  'Lungyao',
  'Lurang',
  'Lusoc',
  'Macael',
  'Macpayasan',
  'Magsaysay',
  'Malabag',
  'Malacaas',
  'Malafang',
  'Malagsing',
  'Malangat',
  'Malangsang',
  'Malanguyod',
  'Malasacas',
  'Malasugui',
  'Malasuso',
  'Malatag',
  'Malatayag',
  'Malawig',
  'Malay',
  'Maliksi',
  'Malindog',
  'Malinu-og',
  'Malipampang',
  'Maliwig',
  'Maliyaya',
  'Malolos',
  'Maloonan',
  'Malugay',
  'Malulueg',
  'Malusog',
  'Malutac',
  'Maluwig',
  'Malyari',
  'Manggahan',
  'Mangkuraw',
  'Manugal',
  'Manuguia',
  'Manumbay',
  'Mapacac',
  'Mapangdan',
  'Mapaniqui',
  'Maparang',
  'Mapaya',
  'Mapidla',
  'Mapigue',
  'Mapili',
  'Mapili North',
  'Mapili South',
  'Mapini',
  'Mapis-Ilaya',
  'Maplamot',
  'Mapli',
  'Maragondon',
  'Marangsi',
  'Marangsi 2',
  'Maranug',
  'Maraoac',
  'Marao',
  'Marao 2',
  'Mararo',
  'Maraungan',
  'Marayang',
  'Marcalan',
  'Mareca',
  'Marelag',
  'Marelak',
  'Marella',
  'Marelya',
  'Marena',
  'Marenang',
  'Marenge',
  'Marengo',
  'Marengni',
  'Marenias',
  'Mareniyan',
  'Marenong',
  'Marensa',
  'Marentau',
  'Marentik',
  'Marenting',
  'Marentipan',
  'Marentog',
  'Marentong',
  'Marentoy',
  'Marentuk',
  'Marenyaw',
  'Marenyong',
  'Marenyongon',
  'Marepetan',
  'Marequita',
  'Marerab',
  'Mareras',
  'Marerek',
  'Mareren',
  'Marereng',
  'Marerfa',
  'Marerfak',
  'Marerka',
  'Marerkat',
  'Marerko',
  'Marerleng',
  'Marermin',
  'Marermit',
  'Marerna',
  'Mareroang',
  'Mareros',
  'Marerot',
  'Marerpan',
  'Marerqui',
  'Marersau',
  'Marersing',
  'Marersip',
  'Marertaa',
  'Marertad',
  'Marertag',
  'Marertap',
  'Marertas',
  'Marertaw',
  'Marertay',
  'Marertec',
  'Marerted',
  'Marerteg',
  'Marertei',
  'Marertem',
  'Marerten',
  'Marerteng',
  'Marerteo',
  'Marertep',
  'Marerteria',
  'Marerteria 1',
  'Marerteria 2',
  'Marertero',
  'Marertero 1',
  'Marertero 2',
  'Marerteros',
  'Marertesa',
  'Marertesag',
  'Marertesang',
  'Marertesap',
  'Marerteso',
  'Marertess',
  'Marerti',
  'Marertico',
  'Marertie',
  'Marertil',
  'Marertin',
  'Marerting',
  'Marertip',
  'Marertiw',
  'Marertiz',
  'Marertizz',
  'Marertm',
  'Marertman',
  'Marertmer',
  'Marertmin',
  'Marertmit',
  'Marertmk',
  'Marertnn',
  'Marertno',
  'Marertns',
  'Marertnw',
  'Marertny',
  'Marerto',
  'Marertob',
  'Marertoe',
  'Marertof',
  'Marertog',
  'Marertoi',
  'Marertoj',
  'Marertok',
  'Marertol',
  'Marertom',
  'Marerton',
  'Marertoo',
  'Marertop',
  'Marertopol',
  'Marertopolis',
  'Marertopo',
  'Marertopos',
  'Marertops',
  'Marertops 1',
  'Marertops 2',
  'Marertopse',
  'Marertoq',
  'Marertoqui',
  'Marertoquin',
  'Marertoquio',
  'Marertoquip',
  'Marertoquipolis',
  'Marertoquis',
  'Marertoquix',
  'Marertoquiy',
  'Marertoquiz',
  'Marertoquizz',
  'Marertoquo',
  'Marertoquon',
  'Marertoquop',
  'Marertoquos',
  'Marertoquoss',
  'Marertoquout',
  'Marertoquow',
  'Marertoquox',
  'Marertoquoy',
  'Marertoquoz',
  'Marertoquozzz',
  'Pantal',
  'Pangalao',
  'Paninipan',
  'Pangasiwaan',
  'Pangayakan',
  'Pangayanan',
  'Panganiban',
  'Pangasinan',
  'Pangayakan East',
  'Pangayakan West',
  'Pania',
  'Paniaon',
  'Panibang',
  'Panibila',
  'Paniblas',
  'Panibuan',
  'Panibungan',
  'Panicbusan',
  'Panicuan',
  'Panicuanan East',
  'Panicuanan West',
  'Panicuasan',
  'Panicuasan East',
  'Panicuasan West',
  'Panicuasang',
  'Paniculan',
  'Paniculas',
  'Panicuwan',
  'Panicyuan',
  'Panidayan',
  'Panideguan',
  'Panidian',
  'Panidihan',
  'Panidiguan',
  'Panidilan',
  'Panidiwan',
  'Paniduagan',
  'Paniduan',
  'Paniduing',
  'Panigalan',
  'Panigayan',
  'Paniganis',
  'Paniganisahan',
  'Panigua',
  'Paniguagan',
  'Panigtagan',
  'Panigtanan',
  'Paniguayan',
  'Panibucan',
  'Panibuean',
  'Panibual',
  'Panibualan',
  'Panibuangan',
  'Panibuan',
  'Panibuanan',
  'Panibuanan East',
  'Panibuanan West',
  'Panibubug',
  'Panibucan',
  'Panibud',
  'Panibudal',
  'Panibudanian',
  'Panibudasan',
  'Panibudayan',
  'Panibudyan',
  'Panibuding',
  'Panibugu',
  'Panibuguian',
  'Panibuguin',
  'Panibukai',
  'Panibukanan',
  'Panibukayan',
  'Panibukian',
  'Panibuko',
  'Panibukong',
  'Panibukoy',
  'Panibukuan',
  'Panibukwahan',
  'Panibulan',
  'Panibulang',
  'Panibulao',
  'Panibulapan',
  'Panibulasan',
  'Panibulawan',
  'Panibulayan',
  'PaniBulbulog',
  'Panibulbulog North',
  'Panibulbulog South',
  'Panibulbunga',
  'Panibulbunga East',
  'Panibulbunga West',
  'Panibuled',
  'Panibuledan',
  'Panibuleding',
  'Panibuleng',
  'Panibulengan',
  'Panibulet',
  'Panibuletan',
  'Panibuletan South',
  'Panibuletan North',
  'Panibuletang',
  'Panibuletig',
  'Panibuletil',
  'Panibuletim',
  'Panibuletip',
  'Panibuletis',
  'Panibuletit',
  'Panibuletix',
  'Panibuletiy',
  'Panibuletiz',
  'Panibuli',
  'Panibulian',
  'Panibuliang',
  'Panibuliao',
  'Panibuliap',
  'Panibuliar',
  'Panibulias',
  'Panibuliatalahan',
];

// Sort and remove duplicates
export const SORTED_BARANGAYS = [...new Set(DAGUPAN_BARANGAYS)].sort();

/**
 * Validate if a barangay is valid
 * @param {String} barangay - Barangay name
 * @returns {Boolean} True if valid barangay
 */
export function isValidBarangay(barangay) {
  if (!barangay || typeof barangay !== 'string') {
    return false;
  }
  return SORTED_BARANGAYS.some(b => b.toLowerCase() === barangay.toLowerCase());
}
